### ISSUE TITLE
No Item Exists for this Item Damage

### ISSUE THREAD

**Issue by SvEgiiVEteR** [SlimeVoid/DynamicTransport#44] opened 2015-11-10 15:54 UTC
[18:52:13] [NEI Item Loading/ERROR] [FML]: No Item Exists for this Item Damage
[18:52:13] [NEI Item Loading/ERROR] [FML]: No Item Exists for this Item Damage
[18:52:13] [NEI Item Loading/ERROR] [FML]: No Item Exists for this Item Damage

and Item no icons except Elevator tool
forge 1541
DynamicTransport-0.1.2.0.jar
SlimevoidLibrary-2.0.4.7.jar

**Comment by wilkemeyer** [comment] 2015-11-17 22:55
it's caused by SlimevoidLibrary
Fixed with SlimeVoid/SlimevoidLibrary/pull/13

Check my fork / releases page if you want to use my build which has the fix already in

**Comment by Tarig0** [comment] 2020-05-08 18:16
Closing due to rewrite for 1.15

**Closed as completed by Tarig0** 2020-05-08 18:16 UTC
